# Generated by Django 4.2.9 on 2024-02-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_tabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=55)),
                ('Email', models.EmailField(max_length=55)),
                ('Number', models.IntegerField(max_length=15)),
                ('Date', models.DateField()),
                ('Person', models.IntegerField(max_length=2)),
            ],
        ),
    ]
